### ISSUE TITLE
Trigger the DALLE 2 image generation API and pass the input user prompt and get/save the resulting image response

### ISSUE THREAD

**Issue by armsp** [sopra-fs23-group-15/envisage-server#31]

**Comment by armsp** [comment]
https://github.com/sopra-fs23-group-15/envisage-server/pull/74

**Comment by nikita-uzh** [comment]
https://github.com/sopra-fs23-group-15/envisage-server/pull/74/commits/b761dedc9233e98ca4cdf789bfef2c4e1c5993e7
