### ISSUE TITLE
weboscket endpoint "/lobbies/{lobbyId}/challengeForRounds/{roundId}" with a new style requirement prompt

### ISSUE THREAD

**Issue by armsp** [sopra-fs23-group-15/envisage-server#36]

**Comment by marion-an** [comment]
08f218ec8b69f9d0e05229d7f0da5b10c572ed5f

**Comment by marion-an** [comment]
76f3c91bd5c0eb85388f7a39aaa887be049f47ff

**Comment by marion-an** [comment]
https://github.com/sopra-fs23-group-15/envisage-client/commit/76f3c91bd5c0eb85388f7a39aaa887be049f47ff
