### ISSUE TITLE
Create Challenge Entity that has StyleRequirement Entity and ImagePrompt Entity

### ISSUE THREAD

**Issue by armsp** [sopra-fs23-group-15/envisage-server#77]

**Comment by armsp** [comment]
Already done the Style Requirement and I think the Challenge class is ready as a template.
Assiginig @marion-an since she wanted to work on the ImagePrompt entity

**Comment by marion-an** [comment]
59c7ef3bf2ba1192949c484d011eeb74c56e5100 commit which concludes this task
